### ISSUE TITLE
EPIC: Account Registration and Management

### ISSUE THREAD

**Issue by NatashaRy** [NatashaRy/pokedex-genius#12]
[As a **new user**, I can **create my own account with a unique username and email** so that **I can personalize my experience and manage my Pokedexes**.](https://github.com/NatashaRy/pokedex-genius/issues/1)

### Acceptance Criteria:

- User can register with a unique username and email.
- System verifies email uniqueness and sends a confirmation email.
- User can complete registration through a confirmation link.
- User can log in and out securely.

### Tasks: 

- [x] [Design registration form (UI).](https://github.com/NatashaRy/pokedex-genius/issues/18)
- [x] [Implement email and username validation logic.](https://github.com/NatashaRy/pokedex-genius/issues/17)
- [x] [Create login and logout functionalities.](https://github.com/NatashaRy/pokedex-genius/issues/10)
- [x] Test security of login/logout processes.
