### ISSUE TITLE
EPIC: Dashboard and Pokedex management

### ISSUE THREAD

**Issue by NatashaRy** [NatashaRy/pokedex-genius#13]
[As a **user**, I can **access a dashboard that displays all my created Pokedexes**, so that **I can easily manage and view my collections**.
](https://github.com/NatashaRy/pokedex-genius/issues/3)

****
### Acceptance Criteria:

- User dashboard displays all created Pokedexes.
- Users can create new Pokedexes with unique names and colors.
- Users can edit and delete their Pokedexes.

-----

### Tasks: 

- [x] [Design user dashboard layout.](https://github.com/NatashaRy/pokedex-genius/issues/20)
- [x] [Implement functionality to display user's Pokedexes.](https://github.com/NatashaRy/pokedex-genius/issues/21)
- [x] [Create features to add, edit, and delete Pokedexes.](https://github.com/NatashaRy/pokedex-genius/issues/4)
- [x] Ensure responsiveness of the dashboard.
