### ISSUE TITLE
EPIC: Pokemon Collection

### ISSUE THREAD

**Issue by NatashaRy** [NatashaRy/pokedex-genius#14]
[As a **user**, I can **add Pokemon to my Pokedexes**, so that **I can keep track of my Pokemon collections**.
](https://github.com/NatashaRy/pokedex-genius/issues/5)

-----

### Acceptance Criteria:

- Users can add Pokemon to any of their Pokedexes.
- Each Pokemon entry shows detailed information.
- Users can favorite specific Pokemon and Pokedexes.

-----

### Tasks: 

- [x] [Implement feature to add Pokemon to Pokedexes.](https://github.com/NatashaRy/pokedex-genius/issues/7)
- [x] [Develop a detailed information view for each Pokemon.](https://github.com/NatashaRy/pokedex-genius/issues/6)
- [x] [Implement function searching for Pokemons](https://github.com/NatashaRy/pokedex-genius/issues/22)
- [x] Ensure data accuracy and completeness for Pokemon information.
