### ISSUE TITLE
EPIC: Community Interaction

### ISSUE THREAD

**Issue by NatashaRy** [NatashaRy/pokedex-genius#15]
[As a **user**, I can **favorite other users’ Pokedexes and certain Pokemon**, so that **I can easily access them later**.
](https://github.com/NatashaRy/pokedex-genius/issues/7)

---

### Acceptance Criteria:

- Users can view other users’ Pokedexes.
- Users can like/unlike other users’ Pokedexes.
- System tracks and displays the number of likes.

---

### Tasks: 

- [ ] [Implement feature to view other users' Pokedexes.](https://github.com/NatashaRy/pokedex-genius/issues/24)
- [ ] [Develop functionality for liking/unliking Pokedexes](https://github.com/NatashaRy/pokedex-genius/issues/8).
- [ ] Design a system to count and display likes.
